# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "scikit-image"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>"
        }
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "<args:1>",
        "add_properties": {
          "cp_physics": True
        },
      }
    },
    {
      "module": "loader.HavenEnvironmentLoader",
      "config": {
        "data_path": "<args:4>"
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
      }
    },
    {
      "module": "loader.CCMaterialLoader",
      "config": {
        "folder_path": "<args:3>",
        "used_assets": ["Bricks", "Wood", "Carpet", "Tile", "Marble", "Concrete"]
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Cube.001"
          }
        },
        "cf_randomize_materials": {
          "randomization_level": 1,
          "materials_to_replace_with": {
            "provider": "getter.Material",
            "random_samples": 4,
            "conditions": {
              "cp_is_cc_texture": True
            }
          }
        },
        "cp_physics": False
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        # get pans
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Cylinder.*"
          }
        },
        # Sets the location of this entity above surface
        "location": {
          "provider": "sampler.UpperRegionSampler",
          "min_height": 0.3,
          "to_sample_on": {
              "provider": "getter.Entity",
              "conditions": {
                "name": "Cube.001"
              }

          }
        },
        # avoid objects falling through other objects during physics simulation
        "cf_add_modifier": {
          "name": "Solidify",
          "thickness": 0.0025
        }
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "solver_iters": 30,
        "substeps_per_frame": 40,
        "min_simulation_time": 0.5,
        "max_simulation_time": 10,
        "check_object_interval": 0.25,
        "mass_scaling": True,
        "mass_factor": 2000,
        "objs_with_box_collision_shape": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Cube.001"
          }
        }
      }
    },
    {
      "module": "lighting.LightSampler",
      "config": {
        "lights": [
          {
            "number_of_samples": 6,
            "location": {
              "provider": "sampler.Shell",
              "center": [1, 2, 3],
              "radius_min": 4,
              "radius_max": 7,
              "elevation_min": 15,
              "elevation_max": 70
              },
              "type": "SUN",
              "energy": 10
          }
        ]
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
        {
          "proximity_checks": {
            "min": 0.3
          },
          "check_if_objects_visible": {
            "provider": "getter.Entity",
            "conditions": {
              "name": "Cylinder.003"
            }
          },
          "excluded_objs_in_proximity_check":  {
            "provider": "getter.Entity",
            "conditions": {
              "name": "Cube.001"
            }
          },
          "number_of_samples": 2,
          "location": {
            "provider": "sampler.Shell",
            "center": {
              "provider": "getter.POI",
              "selector": {
                "provider": "getter.Entity",
                "conditions": {
                  "name": "Cylinder.*"
                }
              }
            },
            "radius_min": 2.0,
            "radius_max": 30.0,
            "elevation_min": 3,
            "elevation_max": 89,
            "uniform_elevation": True
          },
          "rotation": {
            "format": "look_at",
            "value": {
              "provider": "getter.POI",
              "selector": {
                "provider": "getter.Entity",
                "conditions": {
                  "name": "Cylinder.*"
                }
              }
            }
          }
        }
        ]
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": ["instance", "class"]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "glossy_bounces": 30,
        "samples": 50,
        "output_key": "colors",
        "render_normals": True
      }
    },
    {
      "module": "writer.CocoAnnotationsWriter",
      "config": {
      }
    },
    {
      "module": "writer.Hdf5Writer"
    }
  ]
}
