# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "scikit-image"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>"
        }
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "<args:1>"
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": { 
            "cp_category_id": 0  # this guarantees that the object is a mesh, and not for example a camera
          }
        },
        "cp_physics": False,
        "cp_name": "ground_plane"
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": { 
            "cp_category_id": 1  # this guarantees that the object is a mesh, and not for example a camera
          }
        },
        "cp_physics": True
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "number_of_samples": 3,
        "objects_to_sample": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_physics": True,
            "type": "MESH"
          }
        },
        "pos_sampler":{
          "provider":"sampler.Uniform3d",
          "max":[2.5, 2.5, 3],
          "min":[0, 0, 0]
        },
        "rot_sampler":{
          "provider":"sampler.UniformSO3",
          "around_x": False,
          "around_y": False
        }
      }
    },
    {
      "module": "lighting.LightSampler",
      "config": {
        "lights": [
          {
            "number_of_samples": 3,
            "location": {
              "provider": "sampler.Shell",
              "center": [1, 2, 3],
              "radius_min": 4,
              "radius_max": 7,
              "elevation_min": 15,
              "elevation_max": 70
              },
              "type": "POINT",
              "energy": 500
          }
        ]
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 3,
        "max_simulation_time": 10,
        "check_object_interval": 1,
        "solver_iters": 5,
        "collision_shape": "MESH"
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
          {
            "number_of_samples": 3,
            "location": {
              "provider":"sampler.Uniform3d",
              "max":[10, -37, 19],
              "min":[-10, -57, 15]
            },
            "rotation": {
              "format": "look_at",
              "value": {
                "provider": "getter.POI"
              },          
              "inplane_rot": {
                "provider": "sampler.Value",
                "type": "float",
                "min": -0.7854,
                "max": 0.7854
              }
            }
          }
        ]
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": ["instance", "class"]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "samples": 150,
        "output_key": "colors",
        "render_normals": True
      }
    },
    {
      "module": "writer.CocoAnnotationsWriter",
      "config": {
      }
    },
    {
      "module": "writer.Hdf5Writer"
    }
  ]
}
